using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GpsPreview.Maps
{
	// This file was generated by a tool; you should avoid making direct changes.
	// Consider using 'partial classes' to extend these types
	// Input: my.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006


		[global::ProtoBuf.ProtoContract()]
		public partial class Tile : global::ProtoBuf.IExtensible
		{
			private global::ProtoBuf.IExtension __pbn__extensionData;
			global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
				=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

			[global::ProtoBuf.ProtoMember(3, Name = @"layers")]
			public global::System.Collections.Generic.List<Layer> Layers { get; } = new global::System.Collections.Generic.List<Layer>();

			[global::ProtoBuf.ProtoContract()]
			public partial class Value : global::ProtoBuf.IExtensible
			{
				private global::ProtoBuf.IExtension __pbn__extensionData;
				global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
					=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

				[global::ProtoBuf.ProtoMember(1, Name = @"string_value")]
				[global::System.ComponentModel.DefaultValue("")]
				public string StringValue
				{
					get { return __pbn__StringValue ?? ""; }
					set { __pbn__StringValue = value; }
				}
				public bool ShouldSerializeStringValue() => __pbn__StringValue != null;
				public void ResetStringValue() => __pbn__StringValue = null;
				private string __pbn__StringValue;

				[global::ProtoBuf.ProtoMember(2, Name = @"float_value")]
				public float FloatValue
				{
					get { return __pbn__FloatValue.GetValueOrDefault(); }
					set { __pbn__FloatValue = value; }
				}
				public bool ShouldSerializeFloatValue() => __pbn__FloatValue != null;
				public void ResetFloatValue() => __pbn__FloatValue = null;
				private float? __pbn__FloatValue;

				[global::ProtoBuf.ProtoMember(3, Name = @"double_value")]
				public double DoubleValue
				{
					get { return __pbn__DoubleValue.GetValueOrDefault(); }
					set { __pbn__DoubleValue = value; }
				}
				public bool ShouldSerializeDoubleValue() => __pbn__DoubleValue != null;
				public void ResetDoubleValue() => __pbn__DoubleValue = null;
				private double? __pbn__DoubleValue;

				[global::ProtoBuf.ProtoMember(4, Name = @"int_value")]
				public long IntValue
				{
					get { return __pbn__IntValue.GetValueOrDefault(); }
					set { __pbn__IntValue = value; }
				}
				public bool ShouldSerializeIntValue() => __pbn__IntValue != null;
				public void ResetIntValue() => __pbn__IntValue = null;
				private long? __pbn__IntValue;

				[global::ProtoBuf.ProtoMember(5, Name = @"uint_value")]
				public ulong UintValue
				{
					get { return __pbn__UintValue.GetValueOrDefault(); }
					set { __pbn__UintValue = value; }
				}
				public bool ShouldSerializeUintValue() => __pbn__UintValue != null;
				public void ResetUintValue() => __pbn__UintValue = null;
				private ulong? __pbn__UintValue;

				[global::ProtoBuf.ProtoMember(6, Name = @"sint_value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
				public long SintValue
				{
					get { return __pbn__SintValue.GetValueOrDefault(); }
					set { __pbn__SintValue = value; }
				}
				public bool ShouldSerializeSintValue() => __pbn__SintValue != null;
				public void ResetSintValue() => __pbn__SintValue = null;
				private long? __pbn__SintValue;

				[global::ProtoBuf.ProtoMember(7, Name = @"bool_value")]
				public bool BoolValue
				{
					get { return __pbn__BoolValue.GetValueOrDefault(); }
					set { __pbn__BoolValue = value; }
				}
				public bool ShouldSerializeBoolValue() => __pbn__BoolValue != null;
				public void ResetBoolValue() => __pbn__BoolValue = null;
				private bool? __pbn__BoolValue;

			}

			[global::ProtoBuf.ProtoContract()]
			public partial class Feature : global::ProtoBuf.IExtensible
			{
				private global::ProtoBuf.IExtension __pbn__extensionData;
				global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
					=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

				[global::ProtoBuf.ProtoMember(1, Name = @"id")]
				[global::System.ComponentModel.DefaultValue(0)]
				public ulong Id
				{
					get { return __pbn__Id ?? 0; }
					set { __pbn__Id = value; }
				}
				public bool ShouldSerializeId() => __pbn__Id != null;
				public void ResetId() => __pbn__Id = null;
				private ulong? __pbn__Id;

				[global::ProtoBuf.ProtoMember(2, Name = @"tags", IsPacked = true)]
				public uint[] Tags { get; set; }

				[global::ProtoBuf.ProtoMember(3, Name = @"type")]
				[global::System.ComponentModel.DefaultValue(Tile.GeomType.Unknown)]
				public Tile.GeomType Type
				{
					get { return __pbn__Type ?? Tile.GeomType.Unknown; }
					set { __pbn__Type = value; }
				}
				public bool ShouldSerializeType() => __pbn__Type != null;
				public void ResetType() => __pbn__Type = null;
				private Tile.GeomType? __pbn__Type;

				[global::ProtoBuf.ProtoMember(4, Name = @"geometry", IsPacked = true)]
				public uint[] Geometries { get; set; }

			}

			[global::ProtoBuf.ProtoContract()]
			public partial class Layer : global::ProtoBuf.IExtensible
			{
				private global::ProtoBuf.IExtension __pbn__extensionData;
				global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
					=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

				[global::ProtoBuf.ProtoMember(15, Name = @"version", IsRequired = true)]
				public uint Version { get; set; }

				[global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
				public string Name { get; set; }

				[global::ProtoBuf.ProtoMember(2, Name = @"features")]
				public global::System.Collections.Generic.List<Tile.Feature> Features { get; } = new global::System.Collections.Generic.List<Tile.Feature>();

				[global::ProtoBuf.ProtoMember(3, Name = @"keys")]
				public global::System.Collections.Generic.List<string> Keys { get; } = new global::System.Collections.Generic.List<string>();

				[global::ProtoBuf.ProtoMember(4, Name = @"values")]
				public global::System.Collections.Generic.List<Tile.Value> Values { get; } = new global::System.Collections.Generic.List<Tile.Value>();

				[global::ProtoBuf.ProtoMember(5, Name = @"extent")]
				[global::System.ComponentModel.DefaultValue(4096)]
				public uint Extent
				{
					get { return __pbn__Extent ?? 4096; }
					set { __pbn__Extent = value; }
				}
				public bool ShouldSerializeExtent() => __pbn__Extent != null;
				public void ResetExtent() => __pbn__Extent = null;
				private uint? __pbn__Extent;

			}

			[global::ProtoBuf.ProtoContract()]
			public enum GeomType
			{
				[global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
				Unknown = 0,
				[global::ProtoBuf.ProtoEnum(Name = @"POINT")]
				Point = 1,
				[global::ProtoBuf.ProtoEnum(Name = @"LINESTRING")]
				Linestring = 2,
				[global::ProtoBuf.ProtoEnum(Name = @"POLYGON")]
				Polygon = 3,
			}

		}

	

#pragma warning restore CS1591, CS0612, CS3021, IDE1006

}
